// Package repull provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package repull

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for AIOperationOperation.
const (
	ClassifyIntent  AIOperationOperation = "classify-intent"
	GenerateListing AIOperationOperation = "generate-listing"
	PriceSuggestion AIOperationOperation = "price-suggestion"
	RespondToGuest  AIOperationOperation = "respond-to-guest"
	ReviewResponse  AIOperationOperation = "review-response"
)

// Valid indicates whether the value is a known member of the AIOperationOperation enum.
func (e AIOperationOperation) Valid() bool {
	switch e {
	case ClassifyIntent:
		return true
	case GenerateListing:
		return true
	case PriceSuggestion:
		return true
	case RespondToGuest:
		return true
	case ReviewResponse:
		return true
	default:
		return false
	}
}

// Defines values for ConnectStatusStatus.
const (
	ConnectStatusStatusActive   ConnectStatusStatus = "active"
	ConnectStatusStatusError    ConnectStatusStatus = "error"
	ConnectStatusStatusInactive ConnectStatusStatus = "inactive"
)

// Valid indicates whether the value is a known member of the ConnectStatusStatus enum.
func (e ConnectStatusStatus) Valid() bool {
	switch e {
	case ConnectStatusStatusActive:
		return true
	case ConnectStatusStatusError:
		return true
	case ConnectStatusStatusInactive:
		return true
	default:
		return false
	}
}

// Defines values for ConnectionStatus.
const (
	ConnectionStatusActive   ConnectionStatus = "active"
	ConnectionStatusError    ConnectionStatus = "error"
	ConnectionStatusInactive ConnectionStatus = "inactive"
)

// Valid indicates whether the value is a known member of the ConnectionStatus enum.
func (e ConnectionStatus) Valid() bool {
	switch e {
	case ConnectionStatusActive:
		return true
	case ConnectionStatusError:
		return true
	case ConnectionStatusInactive:
		return true
	default:
		return false
	}
}

// Defines values for MessageSenderType.
const (
	MessageSenderTypeGuest  MessageSenderType = "guest"
	MessageSenderTypeHost   MessageSenderType = "host"
	MessageSenderTypeSystem MessageSenderType = "system"
)

// Valid indicates whether the value is a known member of the MessageSenderType enum.
func (e MessageSenderType) Valid() bool {
	switch e {
	case MessageSenderTypeGuest:
		return true
	case MessageSenderTypeHost:
		return true
	case MessageSenderTypeSystem:
		return true
	default:
		return false
	}
}

// Defines values for ReservationPlatform.
const (
	Airbnb     ReservationPlatform = "airbnb"
	BookingCom ReservationPlatform = "booking.com"
	Direct     ReservationPlatform = "direct"
	Other      ReservationPlatform = "other"
	Owner      ReservationPlatform = "owner"
	Vrbo       ReservationPlatform = "vrbo"
	Website    ReservationPlatform = "website"
)

// Valid indicates whether the value is a known member of the ReservationPlatform enum.
func (e ReservationPlatform) Valid() bool {
	switch e {
	case Airbnb:
		return true
	case BookingCom:
		return true
	case Direct:
		return true
	case Other:
		return true
	case Owner:
		return true
	case Vrbo:
		return true
	case Website:
		return true
	default:
		return false
	}
}

// Defines values for ReservationStatus.
const (
	ReservationStatusCancelled ReservationStatus = "cancelled"
	ReservationStatusCompleted ReservationStatus = "completed"
	ReservationStatusConfirmed ReservationStatus = "confirmed"
	ReservationStatusPending   ReservationStatus = "pending"
)

// Valid indicates whether the value is a known member of the ReservationStatus enum.
func (e ReservationStatus) Valid() bool {
	switch e {
	case ReservationStatusCancelled:
		return true
	case ReservationStatusCompleted:
		return true
	case ReservationStatusConfirmed:
		return true
	case ReservationStatusPending:
		return true
	default:
		return false
	}
}

// Defines values for PostV1BillingJSONBodyPlan.
const (
	Growth  PostV1BillingJSONBodyPlan = "growth"
	Scale   PostV1BillingJSONBodyPlan = "scale"
	Starter PostV1BillingJSONBodyPlan = "starter"
)

// Valid indicates whether the value is a known member of the PostV1BillingJSONBodyPlan enum.
func (e PostV1BillingJSONBodyPlan) Valid() bool {
	switch e {
	case Growth:
		return true
	case Scale:
		return true
	case Starter:
		return true
	default:
		return false
	}
}

// Defines values for PostV1ConnectProviderJSONBodyAccessType.
const (
	FullAccess PostV1ConnectProviderJSONBodyAccessType = "full_access"
	ReadOnly   PostV1ConnectProviderJSONBodyAccessType = "read_only"
)

// Valid indicates whether the value is a known member of the PostV1ConnectProviderJSONBodyAccessType enum.
func (e PostV1ConnectProviderJSONBodyAccessType) Valid() bool {
	switch e {
	case FullAccess:
		return true
	case ReadOnly:
		return true
	default:
		return false
	}
}

// Defines values for GetV1ReservationsParamsStatus.
const (
	GetV1ReservationsParamsStatusCancelled GetV1ReservationsParamsStatus = "cancelled"
	GetV1ReservationsParamsStatusCompleted GetV1ReservationsParamsStatus = "completed"
	GetV1ReservationsParamsStatusConfirmed GetV1ReservationsParamsStatus = "confirmed"
	GetV1ReservationsParamsStatusPending   GetV1ReservationsParamsStatus = "pending"
)

// Valid indicates whether the value is a known member of the GetV1ReservationsParamsStatus enum.
func (e GetV1ReservationsParamsStatus) Valid() bool {
	switch e {
	case GetV1ReservationsParamsStatusCancelled:
		return true
	case GetV1ReservationsParamsStatusCompleted:
		return true
	case GetV1ReservationsParamsStatusConfirmed:
		return true
	case GetV1ReservationsParamsStatusPending:
		return true
	default:
		return false
	}
}

// AIOperation defines model for AIOperation.
type AIOperation struct {
	// Input Operation-specific input data
	Input *map[string]interface{} `json:"input,omitempty"`

	// Operation AI operation to perform
	Operation *AIOperationOperation `json:"operation,omitempty"`
}

// AIOperationOperation AI operation to perform
type AIOperationOperation string

// CalendarDay defines model for CalendarDay.
type CalendarDay struct {
	Available *bool               `json:"available,omitempty"`
	Date      *openapi_types.Date `json:"date,omitempty"`
	MinNights *int                `json:"minNights,omitempty"`
	Price     *float32            `json:"price,omitempty"`
}

// ConnectHost Public-facing metadata about the host whose account is linked. Lets clients render an account-level card (avatar + name) instead of just an opaque ID. Email is intentionally NOT exposed for Airbnb — the partner API doesn't return host email.
type ConnectHost struct {
	// ActivationStatus Per-provider activation/onboarding status.
	ActivationStatus *string `json:"activationStatus,omitempty"`

	// AvatarUrl Profile picture URL (small).
	AvatarUrl *string `json:"avatarUrl,omitempty"`

	// AvatarUrlLarge Profile picture URL (large).
	AvatarUrlLarge *string `json:"avatarUrlLarge,omitempty"`

	// DisplayName Short display name (Airbnb first name).
	DisplayName *string `json:"displayName,omitempty"`

	// DisplayNameLong Preferred long-form name. Falls back to displayName when the host hasn't set a preferred form.
	DisplayNameLong *string `json:"displayNameLong,omitempty"`
}

// ConnectStatus Connection status response for a single provider. When `connected` is false, all other fields except `provider` and `host` may be omitted, and `host` is null.
type ConnectStatus struct {
	Connected *bool      `json:"connected,omitempty"`
	CreatedAt *time.Time `json:"createdAt,omitempty"`

	// ExternalAccountId Provider-side account ID (e.g. the Airbnb host ID).
	ExternalAccountId *string `json:"externalAccountId,omitempty"`

	// Host Host metadata, populated for Airbnb when the host row exists. Null for other providers (per-provider enrichment is incremental).
	Host *ConnectHost `json:"host,omitempty"`

	// Id Repull-side connection ID. Stable across token refreshes.
	Id       *int                 `json:"id,omitempty"`
	Provider *string              `json:"provider,omitempty"`
	Status   *ConnectStatusStatus `json:"status,omitempty"`
}

// ConnectStatusStatus defines model for ConnectStatus.Status.
type ConnectStatusStatus string

// Connection defines model for Connection.
type Connection struct {
	CreatedAt         *time.Time `json:"createdAt,omitempty"`
	ExternalAccountId *string    `json:"externalAccountId,omitempty"`

	// Host Host metadata for the linked account. Currently populated for Airbnb only; null for other providers.
	Host     *ConnectHost      `json:"host,omitempty"`
	Id       *int              `json:"id,omitempty"`
	Provider *string           `json:"provider,omitempty"`
	Status   *ConnectionStatus `json:"status,omitempty"`
}

// ConnectionStatus defines model for Connection.Status.
type ConnectionStatus string

// Conversation defines model for Conversation.
type Conversation struct {
	GuestName     *string    `json:"guestName,omitempty"`
	Id            *string    `json:"id,omitempty"`
	LastMessage   *string    `json:"lastMessage,omitempty"`
	LastMessageAt *time.Time `json:"lastMessageAt,omitempty"`
	ReservationId *int       `json:"reservationId,omitempty"`
	UnreadCount   *int       `json:"unreadCount,omitempty"`
}

// Error defines model for Error.
type Error struct {
	Error *struct {
		Code    *string `json:"code,omitempty"`
		DocsUrl *string `json:"docs_url,omitempty"`

		// Example Example of correct usage
		Example *string `json:"example,omitempty"`
		Message *string `json:"message,omitempty"`
	} `json:"error,omitempty"`
}

// Guest defines model for Guest.
type Guest struct {
	Email        *openapi_types.Email `json:"email,omitempty"`
	FirstName    *string              `json:"firstName,omitempty"`
	Id           *int                 `json:"id,omitempty"`
	LastName     *string              `json:"lastName,omitempty"`
	Phone        *string              `json:"phone,omitempty"`
	TotalRevenue *float32             `json:"totalRevenue,omitempty"`
	TotalStays   *int                 `json:"totalStays,omitempty"`
}

// Message defines model for Message.
type Message struct {
	ConversationId *string            `json:"conversationId,omitempty"`
	Id             *string            `json:"id,omitempty"`
	Message        *string            `json:"message,omitempty"`
	SenderName     *string            `json:"senderName,omitempty"`
	SenderType     *MessageSenderType `json:"senderType,omitempty"`
	SentAt         *time.Time         `json:"sentAt,omitempty"`
}

// MessageSenderType defines model for Message.SenderType.
type MessageSenderType string

// PaginatedResponse defines model for PaginatedResponse.
type PaginatedResponse struct {
	Data       *[]interface{} `json:"data,omitempty"`
	Pagination *struct {
		HasMore *bool `json:"hasMore,omitempty"`
		Limit   *int  `json:"limit,omitempty"`
		Offset  *int  `json:"offset,omitempty"`
		Total   *int  `json:"total,omitempty"`
	} `json:"pagination,omitempty"`
}

// Property A vacation rental property from a connected PMS
type Property struct {
	// Address Full address
	Address   *string  `json:"address,omitempty"`
	Bathrooms *float32 `json:"bathrooms,omitempty"`
	Bedrooms  *int     `json:"bedrooms,omitempty"`
	City      *string  `json:"city,omitempty"`
	Country   *string  `json:"country,omitempty"`

	// ExternalId ID in the source PMS
	ExternalId *string `json:"externalId,omitempty"`

	// Id Internal Repull property ID
	Id        *int     `json:"id,omitempty"`
	Latitude  *float32 `json:"latitude,omitempty"`
	Longitude *float32 `json:"longitude,omitempty"`
	MaxGuests *int     `json:"maxGuests,omitempty"`

	// Name Property name
	Name *string `json:"name,omitempty"`

	// Provider Source PMS
	Provider *string `json:"provider,omitempty"`
	State    *string `json:"state,omitempty"`

	// Thumbnail Primary photo URL
	Thumbnail *string `json:"thumbnail,omitempty"`
}

// Reservation A booking/reservation from a connected PMS
type Reservation struct {
	CheckIn  *openapi_types.Date `json:"checkIn,omitempty"`
	CheckOut *openapi_types.Date `json:"checkOut,omitempty"`

	// ConfirmationCode PMS confirmation code
	ConfirmationCode *string              `json:"confirmationCode,omitempty"`
	Currency         *string              `json:"currency,omitempty"`
	GuestCount       *int                 `json:"guestCount,omitempty"`
	GuestEmail       *openapi_types.Email `json:"guestEmail,omitempty"`
	GuestFirstName   *string              `json:"guestFirstName,omitempty"`
	GuestLastName    *string              `json:"guestLastName,omitempty"`
	GuestPhone       *string              `json:"guestPhone,omitempty"`

	// Id Internal Repull reservation ID
	Id *int `json:"id,omitempty"`

	// Platform Booking source
	Platform *ReservationPlatform `json:"platform,omitempty"`

	// PropertyId Property ID
	PropertyId *int               `json:"propertyId,omitempty"`
	Provider   *string            `json:"provider,omitempty"`
	Status     *ReservationStatus `json:"status,omitempty"`
	TotalPrice *float32           `json:"totalPrice,omitempty"`
}

// ReservationPlatform Booking source
type ReservationPlatform string

// ReservationStatus defines model for Reservation.Status.
type ReservationStatus string

// WebhookSubscription defines model for WebhookSubscription.
type WebhookSubscription struct {
	Active *bool     `json:"active,omitempty"`
	Events *[]string `json:"events,omitempty"`
	Id     *string   `json:"id,omitempty"`

	// Secret HMAC-SHA256 signing secret
	Secret *string `json:"secret,omitempty"`
	Url    *string `json:"url,omitempty"`
}

// Limit defines model for limit.
type Limit = int

// Offset defines model for offset.
type Offset = int

// Provider defines model for provider.
type Provider = string

// GetV1AvailabilityPropertyIdParams defines parameters for GetV1AvailabilityPropertyId.
type GetV1AvailabilityPropertyIdParams struct {
	StartDate openapi_types.Date `form:"startDate" json:"startDate"`
	EndDate   openapi_types.Date `form:"endDate" json:"endDate"`
}

// PutV1AvailabilityPropertyIdJSONBody defines parameters for PutV1AvailabilityPropertyId.
type PutV1AvailabilityPropertyIdJSONBody struct {
	Dates *[]CalendarDay `json:"dates,omitempty"`
}

// PostV1BillingJSONBody defines parameters for PostV1Billing.
type PostV1BillingJSONBody struct {
	Plan *PostV1BillingJSONBodyPlan `json:"plan,omitempty"`
}

// PostV1BillingJSONBodyPlan defines parameters for PostV1Billing.
type PostV1BillingJSONBodyPlan string

// PostV1ConnectProviderJSONBody defines parameters for PostV1ConnectProvider.
type PostV1ConnectProviderJSONBody struct {
	// AccessType Airbnb only — selects the OAuth scope set. 'read_only' grants calendar-only access; 'full_access' grants full host scopes (default).
	AccessType *PostV1ConnectProviderJSONBodyAccessType `json:"accessType,omitempty"`

	// ApiKey PMS providers — API key.
	ApiKey *string `json:"apiKey,omitempty"`

	// ClientId Plumguide — client ID.
	ClientId *string `json:"clientId,omitempty"`

	// ClientSecret Plumguide — client secret.
	ClientSecret *string `json:"clientSecret,omitempty"`

	// RedirectUrl Airbnb only — where to redirect the user after the OAuth flow completes.
	RedirectUrl *string `json:"redirectUrl,omitempty"`
}

// PostV1ConnectProviderJSONBodyAccessType defines parameters for PostV1ConnectProvider.
type PostV1ConnectProviderJSONBodyAccessType string

// PostV1ConversationsIdMessagesJSONBody defines parameters for PostV1ConversationsIdMessages.
type PostV1ConversationsIdMessagesJSONBody struct {
	Message string `json:"message"`
}

// GetV1GuestsParams defines parameters for GetV1Guests.
type GetV1GuestsParams struct {
	// Limit Max items per page
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Pagination offset
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`

	// Search Search by name, email, or phone
	Search *string `form:"search,omitempty" json:"search,omitempty"`
}

// GetV1PropertiesParams defines parameters for GetV1Properties.
type GetV1PropertiesParams struct {
	// Limit Max items per page
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Pagination offset
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`

	// Provider Filter by PMS provider
	Provider *string `form:"provider,omitempty" json:"provider,omitempty"`
}

// GetV1ReservationsParams defines parameters for GetV1Reservations.
type GetV1ReservationsParams struct {
	// Limit Max items per page
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Pagination offset
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`

	// Platform Filter by booking platform
	Platform *string                        `form:"platform,omitempty" json:"platform,omitempty"`
	Status   *GetV1ReservationsParamsStatus `form:"status,omitempty" json:"status,omitempty"`

	// CheckInFrom Check-in date range start
	CheckInFrom *openapi_types.Date `form:"checkInFrom,omitempty" json:"checkInFrom,omitempty"`

	// CheckInTo Check-in date range end
	CheckInTo *openapi_types.Date `form:"checkInTo,omitempty" json:"checkInTo,omitempty"`
}

// GetV1ReservationsParamsStatus defines parameters for GetV1Reservations.
type GetV1ReservationsParamsStatus string

// PostV1ReservationsJSONBody defines parameters for PostV1Reservations.
type PostV1ReservationsJSONBody struct {
	CheckIn        openapi_types.Date `json:"checkIn"`
	CheckOut       openapi_types.Date `json:"checkOut"`
	Currency       *string            `json:"currency,omitempty"`
	GuestCount     *int               `json:"guestCount,omitempty"`
	GuestEmail     *string            `json:"guestEmail,omitempty"`
	GuestFirstName string             `json:"guestFirstName"`
	GuestLastName  string             `json:"guestLastName"`
	GuestPhone     *string            `json:"guestPhone,omitempty"`
	PropertyId     int                `json:"propertyId"`
	TotalPrice     *float32           `json:"totalPrice,omitempty"`
}

// PatchV1ReservationsIdJSONBody defines parameters for PatchV1ReservationsId.
type PatchV1ReservationsIdJSONBody struct {
	CheckIn    *openapi_types.Date `json:"checkIn,omitempty"`
	CheckOut   *openapi_types.Date `json:"checkOut,omitempty"`
	Status     *string             `json:"status,omitempty"`
	TotalPrice *float32            `json:"totalPrice,omitempty"`
}

// PostV1WebhooksJSONBody defines parameters for PostV1Webhooks.
type PostV1WebhooksJSONBody struct {
	Events []string `json:"events"`
	Url    string   `json:"url"`
}

// PostV1WebhooksTestJSONBody defines parameters for PostV1WebhooksTest.
type PostV1WebhooksTestJSONBody struct {
	Event     *string `json:"event,omitempty"`
	WebhookId *string `json:"webhookId,omitempty"`
}

// PostV1AiJSONRequestBody defines body for PostV1Ai for application/json ContentType.
type PostV1AiJSONRequestBody = AIOperation

// PutV1AvailabilityPropertyIdJSONRequestBody defines body for PutV1AvailabilityPropertyId for application/json ContentType.
type PutV1AvailabilityPropertyIdJSONRequestBody PutV1AvailabilityPropertyIdJSONBody

// PostV1BillingJSONRequestBody defines body for PostV1Billing for application/json ContentType.
type PostV1BillingJSONRequestBody PostV1BillingJSONBody

// PostV1ConnectProviderJSONRequestBody defines body for PostV1ConnectProvider for application/json ContentType.
type PostV1ConnectProviderJSONRequestBody PostV1ConnectProviderJSONBody

// PostV1ConversationsIdMessagesJSONRequestBody defines body for PostV1ConversationsIdMessages for application/json ContentType.
type PostV1ConversationsIdMessagesJSONRequestBody PostV1ConversationsIdMessagesJSONBody

// PostV1ReservationsJSONRequestBody defines body for PostV1Reservations for application/json ContentType.
type PostV1ReservationsJSONRequestBody PostV1ReservationsJSONBody

// PatchV1ReservationsIdJSONRequestBody defines body for PatchV1ReservationsId for application/json ContentType.
type PatchV1ReservationsIdJSONRequestBody PatchV1ReservationsIdJSONBody

// PostV1WebhooksJSONRequestBody defines body for PostV1Webhooks for application/json ContentType.
type PostV1WebhooksJSONRequestBody PostV1WebhooksJSONBody

// PostV1WebhooksTestJSONRequestBody defines body for PostV1WebhooksTest for application/json ContentType.
type PostV1WebhooksTestJSONRequestBody PostV1WebhooksTestJSONBody
